---
- name: "Docker systemd custom directory is present"
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  become: yes

- name: "Proxy configuration is present"
  template:
    src: proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/proxy.conf
  notify:
    - restart docker
  when: docker_http_proxy != "" or docker_https_proxy != "" or docker_no_proxy != ""
  become: yes

- name: "Insecure Docker registry - RHEL"
  lineinfile:
    path: /etc/sysconfig/docker
    regexp: '^INSECURE_REGISTRY='
    line: "INSECURE_REGISTRY='{{ docker_insecure_registry }}'"
  when: docker_insecure_registry is defined and ansible_os_family == 'RedHat'
  become: yes

- name: "Docker daemon is enabled"
  service:
    name: docker
    enabled: yes
    masked: no
  become: yes

