---
- name: Install Docker Update 
  block:

    - name: Do an update and upgrade for debian family
      apt:
        update_cache: yes
        upgrade: yes

    - name: first round of installs
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-ce-17.12.1.ce-1.el7.centos.x86_64

  when: ansible_os_family == "Debian"

- name: RedHat family yum clean and update
  block:

    - name: Clean yum parts
      command: "{{ ansible_pkg_mgr }} clean all"
      args:
        warn: no

    - name: Remove yum cache dir
      file:
        path: /var/cache/yum
        state: absent

    - name: Perform package update
      action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
      with_items:
        - docker-ce-17.12.1.ce-1.el7.centos.x86_64

  when: ansible_os_family == "RedHat"
