# Play Name: add_docker_repo.yml
# Version: 1.0
#
# Execution Order: 3
#
# Description:
#   This play configures docker and other specific repos for yum
#
# Variables:
#   target_hosts: defaults to all, can be used to play on a host or group of hosts
#
# Group Variables:
#   ../group_vars/docker_vms.yml
#
# Play Dependencies:
#   remove_docker.yml
#
# Role Dependencies:
#   apigw.docker-ce
#   apigw.docker-storage-setup
#   configure-http-proxy
#
# Example usage:
#
#  ansible-playbook -i inventories -u tecnotree -k -K ./playbooks/add_docker_repo.yml
#  ansible-playbook -i inventories -u tecnotree ./playbooks/add_docker_repo.yml
#  ansible-playbook -i inventories ./playbooks/add_docker_repo.yml
#  ansible-playbook -i inventories -u tecnotree ./playbooks/add_docker_repo.yml -e target_hosts=vm1
#
#
---
- hosts: "{{ target_hosts | default('docker_vms')}}"
  gather_facts: yes
  become: yes
  tasks:

    - name: Check the inventory is part of the docker_vms group
      fail:
        msg: "Failed: One or more vms needs to be in docker_vms group for this playbook to work properly!"
      when: inventory_hostname not in groups.docker_vms
    - name: Add repo for Docker
      include_role:
        name: add_docker_repo
