# Play Name: update_docker.yml
# Version: 1.0
#
# Execution Order: 3
#
# Description:
#   This play updates Docker to certain version 
#
# Variables:
#   target_hosts: defaults to all, can be used to play on a host or group of hosts
#   define the desired docker version in ..roles/docker_update/tasks/main.yml and run the play
#
# Group Variables:
#   ../group_vars/docker_vms.yml
#
# Play Dependencies:
#   
#
# Role Dependencies:
# 
#
# Example usage:
#
#  ansible-playbook -i inventories -u tecnotree -k -K ./playbooks/update_docker.yml
#  ansible-playbook -i inventories -u tecnotree ./playbooks/update_docker.yml
#  ansible-playbook -i inventories ./playbooks/update_docker.yml
#  ansible-playbook -i inventories -u tecnotree ./playbooks/update_docker.yml -e target_hosts=vm1
#
#
---
- hosts: "{{ target_hosts | default('docker_vms')}}"
  gather_facts: yes
  become: yes
  tasks:

    - name: Check the inventory is part of the docker_vms group
      fail:
        msg: "Failed: One or more vms needs to be in docker_vms group for this playbook to work properly!"
      when: inventory_hostname not in groups.docker_vms
    - name: Update Packages
      include_role:
        name: docker_update
