---
- name: Check if hostname is an IP
  fail:
    msg: "Error: Host name in the inventory file must not be an IP address!"
  when: inventory_hostname | ipv4('address')

- name: Setup the Recommended sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.set|default('yes') }}"
    state: "{{ item.state|default('present') }}"
    reload: "{{ item.reload|default('no') }}"
    ignoreerrors: yes
  with_items: "{{ update_sysctl }}"

- name: Setup the Recommended kernel sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.set|default('yes') }}"
    state: "{{ item.state|default('present') }}"
    reload: "{{ item.reload|default('no') }}"
    ignoreerrors: yes
  with_items: "{{ update_kernel_sysctl }}"
  when: ansible_virtualization_type != "openvz"

- name: Disable IPv6 in sysconfig/network
  lineinfile: "dest=/etc/sysconfig/network regexp='^{{ item.regexp }}' line='{{ item.line }}'"
  with_items:
   - {regexp: 'NETWORKING_IPV6=.*', line: 'NETWORKING_IPV6=NO'}
   - {regexp: 'IPV6INIT=.*', line: 'IPV6INIT=no'}
  when: ansible_os_family == 'RedHat'

- name: Reload Sysctl
  command: /bin/true
  notify:
    - reload sysctl.conf
    - flush routes

- name: Set hostname based on inventory target host
  hostname:
    name="{{ inventory_hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind

- name: Add additional host items in /etc/hosts
  lineinfile:
   dest: /etc/hosts
   line: "{{ item.ip }}	{{ item.alias }}"
   regexp: "^{{ item.ip }}"
   state: present
  with_items: "{{ external_hosts_list }}"

- name: Ensure hostname and short hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}"
    line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }}"

- name: Redhat | Update sysconfig
  lineinfile:
    dest=/etc/sysconfig/network
    regexp="HOSTNAME="
    line="HOSTNAME={{inventory_hostname}}"
  when: ansible_os_family == 'RedHat'
